#!/usr/bin/env node
/**
 * Build for dsh-advanced-provider-settings.
 *
 * Two artifacts, because a DSH plugin has two halves with different module
 * systems:
 *
 *  - `lib/index.js`  — the HOST half. ESM for Node, loaded by the Cordis
 *    loader. `@deepseek-ai/*` and `node:*` stay external because the running
 *    DSH profile provides them (the shared `~/.dsh/profiles/node_modules`).
 *
 *  - `lib/client.js` — the BROWSER half. DSH's web shell does not load an ES
 *    module for a plugin: it calls `window.__ModuleLoader__.load({ id, factory })`
 *    and the factory receives a `require` restricted to a fixed allow-list
 *    (react, react/jsx-runtime, react-dom, and a few `@deepseek-ai/*` client
 *    packages). We therefore compile the client half to CommonJS and wrap it
 *    in that exact factory envelope, so `require("react")` inside the bundle
 *    resolves to the shell's own React instance rather than a second copy.
 *
 *  - `lib/types/**` — declarations, emitted by `tsc` (see tsconfig.build.json).
 */
import { build } from 'esbuild'
import { rm, mkdir, writeFile, readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'

const run = promisify(execFile)
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))

/** Every module the web shell's allow-list can supply to a client plugin. */
const CLIENT_STATIC_MODULES = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
]

const watch = process.argv.includes('--watch')

await rm(resolve(root, 'lib'), { recursive: true, force: true })
await mkdir(resolve(root, 'lib'), { recursive: true })

/** @type {import('esbuild').BuildOptions} */
const shared = {
  bundle: true,
  sourcemap: true,
  logLevel: 'info',
  minify: false,
  legalComments: 'none',
  target: ['es2022'],
}

// ---------------------------------------------------------------- host half
await build({
  ...shared,
  entryPoints: [resolve(root, 'src/index.ts')],
  outfile: resolve(root, 'lib/index.js'),
  format: 'esm',
  platform: 'node',
  // The running profile supplies every @deepseek-ai package; `@deepseek-ai/schemastery`
  // and friends must not be duplicated into our bundle.
  external: ['@deepseek-ai/*'],
})

// -------------------------------------------------------------- client half
const clientOut = resolve(root, 'lib/client.js')
await build({
  ...shared,
  entryPoints: [resolve(root, 'src/client/index.tsx')],
  outfile: clientOut,
  format: 'cjs',
  platform: 'browser',
  // `react` MUST resolve to the shell's single React instance; bundling a
  // second copy breaks hooks. The @deepseek-ai client packages are supplied
  // by the shell's static-module map, so they are external too.
  external: CLIENT_STATIC_MODULES,
  define: {
    'process.env.NODE_ENV': '"production"',
  },
})

// Wrap the CommonJS output in the loader envelope the web shell expects.
const body = await readFile(clientOut, 'utf8')
const indented = body
  .split('\n')
  .map((line) => (line.length > 0 ? `      ${line}` : line))
  .join('\n')

const wrapped = `// ${pkg.name}@${pkg.version} — browser half.
// Generated by scripts/build.mjs; do not edit. The DSH web shell loads plugin
// clients through this envelope, and the factory's \`require\` is restricted to
// the shell's static-module allow-list.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${indented}
    return module.exports;
  },
});
`
await writeFile(clientOut, wrapped, 'utf8')

// ------------------------------------------------------------------ types
if (!watch) {
  await run('npx', ['tsc', '--project', 'tsconfig.build.json'], { cwd: root })
}

console.log('\nbuilt lib/index.js, lib/client.js, lib/types/')
